### ISSUE TITLE
export data

### ISSUE THREAD

**Issue by PeppeGC** [PeppeGC/Datatable#3]
in custom_left.js (definizione datatable)

Per non esportare dal formato csv (button) le colonne non visibili è stato aggiunto il codice:
{extend: 'csv', exportOptions: {columns: ':visible'}},

Si cerca un forma generale per non replicare questo codice per ogni button definito

**Comment by gianda** [comment]
Definire l'export generico è possibile solo tramite metdodo "exportData":
https://datatables.net/reference/api/buttons.exportData()

Per utilizzare i bottoni csv, excel ecc.. vanno comunque specificate le opzioni di export singolarmente per ciascun button.
